# Generated by Django 4.2.15 on 2024-10-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEstudio',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor_minimo', models.FloatField()),
                ('valor_maximo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Extraccionista',
            fields=[
                ('id_extraccionista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('numero_documento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('especializacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_muestra', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('numero_documento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMed',
            fields=[
                ('cod_unidad_med', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAnalisis',
            fields=[
                ('id_soli_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('id_extraccionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.extraccionista')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id_resultados', models.AutoField(primary_key=True, serialize=False)),
                ('valor_hallado', models.FloatField()),
                ('observaciones', models.TextField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.estadoestudio')),
                ('id_muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.muestra')),
                ('id_soli_analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.solicitudanalisis')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.tipodocumento'),
        ),
        migrations.CreateModel(
            name='HistorialSolicitud',
            fields=[
                ('id_historial_soli', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('fecha_receta', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.estadosolicitud')),
                ('id_soli_analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.solicitudanalisis')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstudios',
            fields=[
                ('id_historial_estu', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.estadoestudio')),
                ('id_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.estudios')),
            ],
        ),
        migrations.AddField(
            model_name='extraccionista',
            name='id_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.tipodocumento'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='cod_unidad_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.unidadmed'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='id_metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labquim.metodo'),
        ),
    ]
