# Generated by Django 4.2.15 on 2024-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labquim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=100)),
            ],
        ),
    ]
