# Generated by Django 5.0.6 on 2024-10-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labquim', '0003_estudios_id_estado_estudio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudios',
            name='id_estado_estudio',
        ),
        migrations.RemoveField(
            model_name='solicitudanalisis',
            name='id_estado_solicitud',
        ),
    ]
